### PR TITLE
Centos 6

### PR DESCRIPTION
**Pull request by jimbydamonk**
This add centos 6 support. Tested with test kitchen to make sure it didn't break cento 7 or Ubuntu.

### CODE REVIEW

**Comment by savagegus** [comment]
This has merge conflicts at the moment, let me know if you don't have time to resolve them and I'll take a look.

**Comment by jimbydamonk** [comment]
Arg. Should have checked that before I push. Let me take a peek.

**Comment by jimbydamonk** [comment]
Ahh. the centos 7 merge removed the dependency on __franklinkim.nginx__. I am not sure if that was intended or not. 

I added a similar dependency for a centos working nginx role that works the same way. 
So I can either:
- Remove all dependencies (Like the centos merge)
- Put back the old one and my new one

Thoughts?

**Comment by savagegus** [comment]
If you have time to putting them back would be awesome. Not everyone is using it but I think it's fairly userful.

**Comment by jimbydamonk** [comment]
Done.

**Pull request merged**
