### PR TITLE
Adding Centos Support

### PR DESCRIPTION
**Pull request by mhamrah**
I'm happy I came across this repo- I recently had to add Consul support for Centos, and found this the best starting point. I'm new to Ansible, and had to make some semi-opinionated choices to get it working, but I wanted to put it out there in case you were interested.

* Add support for Centos
* Removed NGINX requirement for UI. The ```franklinkim.nginx``` doesn't exist on ansible-galaxy (I couldn't install as a req) nor did I need/want NGINX. Instead, the UI option just enables the UI, and I modified the NGINX support to do a config only, assuming NGINX is already installed. 
* Made Consulate optional (I didn't need this, and seemed to have some install issues)
* Added 127.0.0.1 to /etc/resolve.conf; otherwise, I couldn't get dnsmasq working out-of-box with consul.

Feedback appreciate, or feel free to disregard if you're not interested.

Mike

### CODE REVIEW

**Comment by kenjiskywalker** [comment]
:+1:  this PR.

**Comment by savagegus** [comment]
Anyone interested in dusting this off and getting it working?

**Comment by trumant** [comment]
@savagegus - If I thought I'd ever end up using the role on CentOS, I would be inclined to. Since that's not the case, I'll merely suggest that whomever does pick it up, take advantage of the TestKitchen setup and adds in:

```yml
- name: centos66
    driver_config:
      box: chef/centos-6.6
      box_url: https://atlas.hashicorp.com/chef/boxes/centos-6.6
```

or similar to the platforms list so we can at least determine if the existing test suite passes on CentOS.

**Comment by trumant** [comment]
I'm picking this back up and seeing how far I can get on CentOS 7 and 6.6 with TestKitchen.

**Comment by trumant** [comment]
@savagegus and @mhamrah - So, far this is what I've got to add.

https://github.com/trumant/ansible-consul/commits/centos_support

Once I've validated that the CentOS 7 TestKitchen tests are passing and that things look sane, I'll open a PR with just those changes. If/once that is merged, we should be able to add tests/support for CentOS 6.6 or 6.7 as well.

Only major issue I've encountered so far is that the dynamic bind address feature that works in Ubuntu, fails in CentOS 7 due to the differences in interface naming conventions.

**Comment by savagegus** [comment]
I imagine nginx will be a problem as well.

On Nov 10, 2015, at 2:33 PM, Travis Truman <notifications@github.com<mailto:notifications@github.com>> wrote:


@savagegus<https://github.com/savagegus> and @mhamrah<https://github.com/mhamrah> - So, far this is what I've got to add.

https://github.com/trumant/ansible-consul/commits/centos_support

Once I've validated that the CentOS 7 TestKitchen tests are passing and that things look sane, I'll open a PR with just those changes. If/once that is merged, we should be able to add tests/support for CentOS 6.6 or 6.7 as well.

Only major issue I've encountered so far is that the dynamic bind address feature that works in Ubuntu, fails in CentOS 7 due to the differences in interface naming conventions.

**Comment by trumant** [comment]
Combined the work that was done here with some of my own work to produce #70

**Pull request merged**
