### PR TITLE
Match defaults with Consul defaults

### PR DESCRIPTION
**Pull request by robbiet480**
As per [the docs](https://www.consul.io/docs/agent/options.html#ports) the HTTPS API is disabled by default, DNS on 8600, HTTP on 8500.

### CODE REVIEW

**Comment by savagegus** [comment]
If you want to clean up the conflict I'd be happy to merge this guy too.

**Comment by robbiet480** [comment]
@savagegus All fixed!

**Comment by robbiet480** [comment]
Okay, I haven't had enough coffee yet today, because that's the second time I pushed something without actually fixing the commit. Fix incoming

**Comment by savagegus** [comment]
Thanks man I appreciate the work.

**Pull request merged**
